name: build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@v1.20
      - name: Run build
        run: make build
      # - name: Run and upload coverage to codecov.io
      #   run: make coverage coverage-upload
